### ISSUE TITLE
ios11 bug

### ISSUE THREAD

**Issue by killer3392** [Jonhory/AddressPickerView#1]
ios11下按钮点击无响应

**Comment by killer3392** [comment]
换成UIBarButtonItem可正常响应

**Comment by Jonhory** [comment]
请问你的手机型号是什么，我这边用模拟器6s，8都正常

**Comment by killer3392** [comment]
5s真机，se模拟器

**Comment by killer3392** [comment]
xcode9，swift3.2

**Comment by Jonhory** [comment]
1.用的是这个库还是Swift版本的库？2.用的是混编吗？

**Comment by killer3392** [comment]
oc库混编，没有崩溃，只是点击没反应

**Comment by killer3392** [comment]
可能是xcode9编译器问题，之前用xcode8没问题

**Comment by Jonhory** [comment]
你能发一个demo给我吗？ jonhory@163.com。 我这边自己弄了demo，Xcode9, swift3.2混编，没问题
